// File generated by Firebase configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkbe-RgvnYhFjIVCc11NpCMS7P1vu3k80',
    appId: '1:1083708041409:android:94fd64c30f0d8984384c40',
    messagingSenderId: '1083708041409',
    projectId: 'complain-app-b32bb',
    storageBucket: 'complain-app-b32bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbe-RgvnYhFjIVCc11NpCMS7P1vu3k80',
    appId: '1:1083708041409:ios:placeholder',
    messagingSenderId: '1083708041409',
    projectId: 'complain-app-b32bb',
    storageBucket: 'complain-app-b32bb.firebasestorage.app',
    iosBundleId: 'inc.complain.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbe-RgvnYhFjIVCc11NpCMS7P1vu3k80',
    appId: '1:1083708041409:macos:placeholder',
    messagingSenderId: '1083708041409',
    projectId: 'complain-app-b32bb',
    storageBucket: 'complain-app-b32bb.firebasestorage.app',
    iosBundleId: 'inc.complain.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkbe-RgvnYhFjIVCc11NpCMS7P1vu3k80',
    appId: '1:1083708041409:windows:placeholder',
    messagingSenderId: '1083708041409',
    projectId: 'complain-app-b32bb',
    storageBucket: 'complain-app-b32bb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkbe-RgvnYhFjIVCc11NpCMS7P1vu3k80',
    appId: '1:1083708041409:web:placeholder',
    messagingSenderId: '1083708041409',
    projectId: 'complain-app-b32bb',
    storageBucket: 'complain-app-b32bb.firebasestorage.app',
  );
}
